spring:
  application:
    name: petfriends

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: almoxarifado-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: transporte-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

